name: health_hack
description: Health Hack - An Application for DBA&D Course
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  mysql_client: ^0.0.27
  flutter_svg: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Black.ttf
          weight: 900

  uses-material-design: true